config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :clothes do
    resources :favorites, only: [:create, :destroy, :index]
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  validates :image_first,  presence: true
  validates :gender,  presence: true
  validates :height,  presence: true
  validates :content, length: { maximum: 350 }
  belongs_to :user
  has_many :clothe_labels, dependent: :destroy
  has_many :labels, through: :clothe_labels, source: :label
  has_many :favorites, dependent: :destroy
  enum gender: {girl: 0,boy: 1}
  enum height: {〜80cm: 0, 〜90cm: 1, 〜100cm: 2,  〜110cm: 3, 〜120cm: 4, 〜130cm: 5, 〜140cm: 6, 〜150cm: 7 }
  
  mount_uploader :image_first, ImageUploader
  mount_uploader :image_second, ImageUploader
  mount_uploader :image_third, ImageUploader
  
  scope :search_gender, ->(params) {
    return if params.blank?
    where(gender: params)
    
  }
  
  scope :search_height, ->(params) {
    return if params.blank? 
    where(height: params)
  }
  
  scope :search_label, ->(params) { 
    return if params.blank?
      joins(:labels).where(labels: {content: params}) 
      
  }
  
  scope :search_clothes, -> (params) do
    if params[:search].present?
       search_gender(params[:gender])
      .search_height(params[:height])
      .search_label(params[:label_id])
    end
  end

  
  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/models/clothe_label.rb
class ClotheLabel < ApplicationRecord
  belongs_to :clothe
  belongs_to :label
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :clothe, counter_cache: :favorite_count
  validates :user_id, :uniqueness => {:scope => :clothe_id}
end
 

app/models/label.rb
class Label < ApplicationRecord
  validates :content, presence: true
  validates :content, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :clothes
  has_many :favorites, dependent: :destroy
  has_many :clothes, through: :favorites, source: :clothe
  validates :name,  presence: true, length: { maximum: 30 }
  before_validation{ email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_current_user
  before_action :login_required
  
  private
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def login_required
    redirect_to new_session_path unless @current_user
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:update, :index, :show]
  before_action :ensure_correct_user, only: [:edit, :update,:destroy]
  PER = 9
  def new
    if params[:back]
      @clothe = Clothe.new(clothe_params)
    else
      @clothe = Clothe.new
    end
  end

  def index
    @clothes = Clothe.all.order(created_at: "DESC") 
    @searched_clothes = @clothes.search_clothes(params)
    @paged_clothes = @searched_clothes.page(params[:page]).per(PER)
    @favorite = Favorite.find_by(user_id: current_user.id, clothe_id: params[:id]) if logged_in?
    
  end
  
  def confirm
    @clothe = Clothe.new(clothe_params)
    @clothe.user_id = current_user.id
    render :new if @clothe.invalid?
  end

  def create
    @clothe = Clothe.new(clothe_params)
    @clothe.user_id = current_user.id
    if @clothe.save
      flash[:success] = "新規投稿。"
      redirect_to clothes_path
    else
      render 'new'
    end
  end
  
  def edit;end

  def update
    @clothe.user_id == current_user.id
    if @clothe.update(clothe_params)
      redirect_to clothes_path
    else
      render 'edit'
    end
  end 

  def show
  end	
  
  def destroy
    @clothe.destroy
    redirect_to user_path(@clothe.user_id), notice: '投稿を削除しました。'
  end

  private

  def clothe_params
    params.require(:clothe).permit(:id, :image_first, :image_second, :image_third, 
                                   :image_first_cache, :image_second_cache, :image_third_cache,
                                   :gender, :height, :content, :user_id, label_ids: [])
  end
  
  def set_clothe
    @clothe = Clothe.find(params[:id])
  end

  def ensure_correct_user
    redirect_to clothes_path unless @clothe.user_id == current_user.id
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_clothe, only: [:create, :destroy]
  def index 
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all.order(created_at: "DESC")
	end
  
  def create
    @favorite = Favorite.create(user_id: current_user.id, clothe_id: params[:clothe_id])
    @favorites = Favorite.where(clothe_id: params[:clothe_id])
    @clothe.reload
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, clothe_id: params[:clothe_id])
    favorite.destroy
    @favorites = Favorite.where(clothe_id: params[:clothe_id])
    @clothe.reload
  end

  # private

  def set_clothe
    @clothe = Clothe.find(params[:clothe_id])
  end
  # def create
  #   @clothe = Clothe.find(params[:clothe_id])
  #   @favorite = Favorite.create(user_id: current_user.id, clothe_id: params[:clothe_id])
  #   @clothe.reload
  # end

  # def destroy
  #   @clothe = Clothe.find(params[:article_id])
  #   @favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:article_id])
  #   @favorite.destroy
  #   @clothe.reload
    
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new;end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to clothes_path(user.id)
    else
      redirect_to new_session_path, notice: 'Emailアドレス、パスワードをもう一度確認し実行してください。'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :logged_in, only: [:new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to clothes_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @clothes = Clothe.where(user_id: @user.id).all.order(created_at: 'DESC')
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in
    if logged_in?
      redirect_to clothes_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clothes/confirm.html.erb
<div class="confirm" style="margin-top: 300px; text-align: center;">
  <h3 style="text-align: center;">確認画面</h3>
    <%= form_with(model: @clothe, url: clothes_path,local: true) do |form| %>
        身長: <%= @clothe.height %>
        <br>
        性別: <%= @clothe.gender %>
        <br>
      <%= form.label :コメント %>
        <div class = "well well-sm check">
          <pre><%= simple_format(@clothe.content) %></pre>
        </div>
      <%= form.collection_check_boxes(:label_ids, Label.all, :id, :content) do |b|%>
        <%= b.label { b.check_box + b.text }%>
      <% end %>
      <br>
      <%= form.submit t('view.post'),class: 'btn btn-light' %>
      <%= form.hidden_field :image_first_cache %>
      <%= form.hidden_field :image_second_cache %>
      <%= form.hidden_field :image_third_cache %>
      <%= form.hidden_field :height %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :gender %>
    <% end %>
    
    <%= form_with(model:@clothe, url:new_clothe_path, local:true, method: "get") do |form| %>
      <%= form.hidden_field :image_first_cache %>
        <% if @clothe.image_second.present?%>
          <%= form.hidden_field :image_second_cache %>
        <% end %>
        <% if @clothe.image_third.present?%>
          <%= form.hidden_field :image_third_cache %>
        <% end %>
      <%= form.hidden_field :content %>
      <br>
      <%= form.submit "戻る", name: "back", class: 'btn btn-light', style: 'margin-top: 3px;'%>
    <% end %>     
    <br>
      <div class="container">
        <div class="row">
          <div class="col-md-4" >
            <div class="card_clothe_show">
              <%= image_tag @clothe.image_first.to_s, class: "index_image", :size => "320x320" %>
            </div>
          </div>
          <% if @clothe.image_second.present?%>
            <div class="col-md-4" >
              <div class="card_clothe_show">
                <%= image_tag @clothe.image_second.to_s, class: "index_image", :size => "320x320" %>
              </div>
            </div>
          <% end %>
          <% if @clothe.image_third.present?%>
            <div class="col-md-4" >
              <div class="card_clothe_show">
                <%= image_tag @clothe.image_third.to_s, class: "index_image", :size => "320x320"%>
              </div>
            </div>
          <% end %>
      </div>
    </div>
</div>
  

app/views/clothes/edit.html.erb
<% if @clothe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@clothe.errors.count,"件") %>のエラーが発生しました。 </h2>
    <ul>
    <% @clothe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class = "clothes_index">
    <%= form_with(model: @clothe, local: true) do |form| %>
      <div class="clothes_image">
        <%= form.file_field :image_first%>
        <br>
        <%= form.file_field :image_second %>
        <br>
        <%= form.file_field :image_third %>
      </div>
      <div class="clothes_gender">
        <%= form.label :gender %>
        <br>
        <%= form.select :gender, Clothe.genders.keys, class: 'form-control'%>
      </div>
      <div class="clothes_height">
        <%= form.label :height %>
        <br>
        <%= form.select :height, Clothe.heights.keys, class: 'form-control'%>
      </div>
      <div class="clothes_content">
        <%= form.label :content %>
        <br>
        <%= form.text_area :content, class: 'form-control',id: 'new_content'%>
      </div>
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :content) do |b|%>
          <%= b.label { b.check_box + b.text }%>
        <% end %>
      <br>
      <%= form.submit t('view.post'), class: "btn btn-light" %>
    <% end %>
    <br>
  <%= link_to t('view.back'), user_path(id: @clothe.user_id),class: "btn btn-light" %>
</div>

app/views/clothes/index.html.erb
<div id="search", style="text-align: center; margin-top: 260px;">
  <%= form_with(model: @clothe, method: :get, local: true, url: clothes_path) do |form| %>
    <%= form.label :gender, t('view.gender') %>
    <%= form.select :gender, Clothe.genders.keys,include_blank: true,class: 'round' %>
    
    <%= form.label :height, t('view.height')%>
    <%= form.select :height, Clothe.heights.keys,include_blank: true,class: 'round' %>
  
    <%= form.label :label, 'シーン' %>
    <%= form.select :label_id, Label.all.map {|t| t.content} ,include_blank: true, class: 'round' %>
    <%= form.hidden_field :search, value: 'true' %>
    <%= form.submit t('view.search'), class: "btn-default"%>
  <% end %>
</div>

<div class="container" >
  <div class="row">
    <% @paged_clothes.each do |clothe| %>
    <div class= "col-md-4 col-xs-12", style="height: 35rem">
    <div class="card_index" style="width: 20rem;">
        <div class="card-header">
            <div id = "index_name"> 
              投稿者: <%= link_to "#{clothe.user.name}", user_path(id: clothe.user_id) %>
            </div>
        </div>
        <%= link_to t('view.show'), clothe_path(clothe.id), class: "btn btn-default", style:"float: right;" %>
        
        <% if logged_in? %>
          
          <% if clothe.user_id != current_user.id %>
            <div id="favorites_buttons_<%= clothe.id %>">
              <%= render partial: 'favorites/favorite', locals: { clothe: clothe, favorites: @favorites} %>
            </div>
  
          <% elsif clothe.user_id == current_user.id  %>
        
            <%if clothe.favorite_count.present? %>
              <div class="vertical_like">
                <i class="fas fa-heart", style="color: red; float: left; margin-top: 8px;"></i>
                  <span class="red-text">             
                    <%= clothe.favorite_count %>
                  </span>
              </div>
            <% else %>
              <div class="vertical_like">
                <i class="fas fa-heart", style="color: red; float: left; margin-top: 8px;"></i>
                  <span class="red-text">             
                    <%= "0" %>
                  </span>
              </div>
            <% end %>
          
          <% end %>
        
        <% else %>
          <%if clothe.favorite_count.present? %>
            <div class="vertical_like">
                <i class="fas fa-heart", style="color: red; float: left; margin-top: 8px;"></i>
              <span class="red-text">             
                <%= clothe.favorite_count %>
              </span>
            </div>
            <p style="float: left">loginでいいねできます。</p>
          <% else %>
        
            <div class="vertical_like">
              <i class="fas fa-heart", style="color: red; float: left; margin-top: 8px;"></i>
              <span class="red-text">             
                <%= "0" %>
              </span>
            </div>
            <p style="float: left">loginでいいねできます。</p>
          <% end %>
        <% end %>
        <div class="card-body" >
          <%= image_tag clothe.image_first.to_s, class: "index_image", :size => "310x310" %>
          <%= clothe.height %>
          <br>
          <% if clothe.labels.present? %>
          シーン別:
            <% clothe.labels.each do |a| %>
               <label style="background-color: pink; height: 22px; border-radius: 15%;"><%=  a.content %></label>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer" style="height: 5rem;">  
            <%= "コメント" %> 
            <%= simple_format(clothe.content) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="page", style="margin-top: 50px; float: left; margin-bottom: 20px;">
    <%= paginate @paged_clothes %>
    <%= page_entries_info @paged_clothes %>
  </div>
</div>

app/views/clothes/new.html.erb
<div class = "clothes_index">
    <%= form_with(model: @clothe, local: true, url: confirm_clothes_path) do |form| %>
    <% if @clothe.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(@clothe.errors.count, "件") %> のエラーが発生しました。</h4>
        <ul>
        <% @clothe.errors.full_messages.each do |message| %>
           <li><%= message %></li>
        <% end %>
        </ul>
      </div>
<% end %>
      <div class="clothes_image">
        <%= form.file_field :image_first %>
        <%= form.hidden_field :image_first_cache %>
        <br>
        <%= form.file_field :image_second %>
        <%= form.hidden_field :image_second_cache %>
        <br>
        <%= form.file_field :image_third %>
        <%= form.hidden_field :image_third_cache %>
      </div>
      <div class="clothes_gender">
        <%= form.label :gender, t('view.gender') %>
        <br>
        <%= form.select :gender, Clothe.genders.keys, class: 'form-control'%>
      </div>
      <div class="clothes_height">
        <%= form.label :height , t('view.height') %>
        <br>
        <%= form.select :height, Clothe.heights.keys, class: 'form-control'%>
      </div>
      <div class="clothes_content">
        <%= form.label :content, t('view.content') %>
        <br>
        <%= form.text_area :content, class: 'form-control',id: 'new_content'%>
      </div>
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :content) do |b|%>
          <%= b.label { b.check_box + b.text }%>
        <% end %>
      <br>
      <%= form.submit t('view.confirm'), class: "btn btn-light" %>
      <br>
      <br>
      <%= link_to t('view.back'), clothes_path,class: "btn btn-light" %>
    <% end %>
    <br>
</div>

app/views/clothes/show.html.erb
<h4 style="text-align: center; margin-top: 300px;">投稿詳細</h4>
<p id = "notice"><%= notice %></p>
  <div class="clothe_show" >
    <% if @clothe.labels.present? %>
    <p style="font-size: 20px;">シーン別:
      <% @clothe.labels.each do |a| %>
        <label style="background-color: pink; height: 22px; border-radius: 15%;"><%=  a.content %>,</label>
      <% end %>
    <% end %>
        身長: <%= @clothe.height %>,
        <%= @clothe.gender %>
    </p>
        <%= "コメント" %>  
          <div class="box16 line-break">
            <p><%= simple_format(@clothe.content) %></p>
          </div>
  </div>
      <div class="container">
        <div class="row">
          <div class="col-md-4" >
            <div class="card_clothe_show">
              <%= image_tag @clothe.image_first.to_s, :size => "320x320" ,style: "object-fit: cover;"%>
            </div>
          </div>
          <% if @clothe.image_second.present?%>
            <div class="col-md-4" >
              <div class="card_clothe_show">
                <%= image_tag @clothe.image_second.to_s,  :size => "320x320", style: "object-fit: cover;" %>
              </div>
            </div>
          <% end %>
          <% if @clothe.image_third.present?%>
            <div class="col-md-4" >
              <div class="card_clothe_show">
                <%= image_tag @clothe.image_third.to_s,  :size => "320x320", style: "object-fit: cover;" %>
              </div>
            </div>
          <% end %>
          <div class="clothe_show" style="height: 7rem;">  
            
          </div>
        </div>
      </div>
  </div>

app/views/favorites/_favorite.html.erb
<% if logged_in? %>

  <% unless clothe.favorite_user(current_user.id).blank? %>
    <%= link_to clothe_favorite_path(clothe_id: clothe.id ,id: clothe.favorites[0].id),id: "unfavorite_button", method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="fas fa-heart", style="color: red;"></i>
          <span class="red-text">             
            <%= clothe.favorite_count %>
          </span>
      </div>
    <% end %>

  <% else %>
    <%= link_to clothe_favorites_path(clothe.id), id: "favorite_button",method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="far fa-heart"></i>
          <span class="grey-text text-darken-2">
            <%= clothe.favorite_count %>
          </span>
      </div>
    <% end %>
  <% end %>

<% end %>

  

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @clothe.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {clothe: @clothe}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @clothe.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {clothe: @clothe}) %>");

app/views/favorites/index.html.erb
<h5 style="text-align: center; margin-top: 300px;"><%= "#{@user.name}さんのいいね一覧" %></h5>

<div class="container">
  <div class="row">
    <% @favorites.each do |favorite| %>
    <div class= "col-md-4 col-xs-12", style="height: 35rem">
      <div class="card_index" style="width: 20rem;">
        <div class="card-header">
            <div id = "index_name"> 
              投稿者: <%= link_to "#{favorite.clothe.user.name}", user_path(id: favorite.clothe.user_id) %>
            </div>
        </div>
        <%if favorite.clothe.favorite_count.present? %>
          <div class="vertical_like">
            <i class="fas fa-heart", style="color: red; float: left; margin-top: 4px;"></i>
              <span class="red-text">             
                <%= favorite.clothe.favorite_count %>
              </span>
          </div>
        <% end %>
        <%= link_to "詳細", clothe_path(favorite.clothe.id), class: "btn btn-default", style:"float: left;" %>
        <div class="card-body", style:"height: 40rem;" >
          <%= image_tag favorite.clothe.image_first.to_s, class: "index_image", :size => "310x310" %>
          <%= favorite.clothe.height %>
          <br>
          <% if favorite.clothe.labels.present? %>
          シーン別:
            <% favorite.clothe.labels.each do |a| %>
               <label style="background-color: pink; height: 22px; border-radius: 15%;"><%=  a.content %></label>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer" style="height: 5rem;">  
            <%= "コメント" %> 
            <%= simple_format(favorite.clothe.content) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coordi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width">
  </head>
  
  <body>
    <header>
      <% if logged_in? %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete, class: 'btn btn-default prof',style: "color: white;" %>
      <% else %>
        <%= link_to "Sign up", new_user_path, class: 'btn btn-default prof', style: "color: white;" %>
        <%= link_to "Login", new_session_path, class: 'btn btn-default prof', style: "color: white;"%>
      <% end %>
        <h2 style="margin-top: 50px; margin-left: 30px; color: white;">Coordi</h2>
        <p style="margin-left: 30px; color: white;">何着てどこいく？</p>
    
    <nav class="navbar navbar-expand-md  navbar-light bg-light">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="bs-navi">
        <ul class="navbar-nav">
          <li style="margin-left: 30px;"><%= link_to "投稿一覧", clothes_path, class:"nav-link" %></li>
        <% if logged_in? %>
          <li style="margin-left: 30px;"><%= link_to "投稿作成", new_clothe_path, class:"nav-link" %></li>
          <li style="margin-left: 30px;"><%= link_to "マイページ", user_path(current_user.id), class:"nav-link" %></li>
          <li style="margin-left: 30px;"><%= link_to "いいね一覧", clothe_favorites_path(current_user.id), class:"nav-link" %></li>
        <% end %>
        </ul>
      </div>
    </nav>
    
    </header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
  <%= yield %>
    <div id="back-to-top" style="position:fixed;right:25px;bottom:5px">
      <a href="#"><i class="far fa-hand-pointer fa-3x"></i></a>
    </div>
  </body>
</html>

app/views/users/new.html.erb
  <section id = "signup" >
    <h2>Sign up</h2>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="container-fluid">
        <% if @user.errors.any? %>
            <div id="error_explanation">
             <h4><%= pluralize(@user.errors.count, "件") %>のエラーが発生しました。</h4>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
            </ul>
      </div>
    <% end %>
      <%= f.label :name %>
      <%= f.text_field :name , class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'%>
      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control' %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation , class: 'form-control' %>
      <br>
      <p><%= f.submit "アカウント作成", class: 'btn btn-light' %></p>
    <% end %>
  </section>
</div>

app/views/users/show.html.erb
<h5 style="text-align: center; margin-top: 300px;"><%= "#{@user.name}さんの投稿一覧" %></h5>

<div class="container", style="margin-top: 40px;">
  <div class="row">
    <% @clothes.each do |clothe| %>
    <div class= "col-md-4", style="height: 35rem">
      <div class="card_user" style="width: 20rem;">
        
        <div class="card-body", style="height: 27rem;">
          <%if clothe.favorite_count.present? %>
            <div class="vertical_like">
              <i class="fas fa-heart", style="color: red; float: left; margin-top: 8px;"></i>
                <span class="red-text">             
                  <%= clothe.favorite_count %>
                </span>
            </div>
          <% end %>
          <%= link_to "詳細", clothe_path(clothe.id), class: "btn btn-default" %>
          <% if logged_in? && clothe.user_id == current_user.id %>  
            <%= link_to 'Edit', edit_clothe_path(clothe.id), class: "btn btn-default", style: "color: blue; float: right;" %>
            <%= link_to 'Destroy',clothe_path(clothe.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default", style: "color: red; float: right;"%>
          <% end %>
          <%= image_tag clothe.image_first.to_s, class: "index_image", :size => "310x310" %>
          <%= clothe.height %>
          <br>
          <% if clothe.labels.present? %>
          シーン別:
            <% clothe.labels.each do |a| %>
               <label style="background-color: pink; height: 22px; border-radius: 15%;"><%=  a.content %></label>
            <% end %>
          <% end %>
        </div>
        
        <div class="card-footer" style="height: 5rem;">  
          <%= "コメント" %>  
          <div id = "content">
            <%= simple_format(clothe.content) %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>